sudo: required
language: go
go:
  - "1.15"

services:
  - docker

script:
  - make clean build
  - make ci
  - test $TRAVIS_BRANCH = "master" && docker build --rm --no-cache -t varakh/gan-server:latest .
  - test $TRAVIS_BRANCH = "master" && echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - test $TRAVIS_BRANCH = "master" && docker push varakh/gan-server:latest
