sudo: required
language: go
go:
  - "1.15"

services:
  - docker

script:
  - make clean build
  - make ci

#after_success:
#  - test $TRAVIS_BRANCH = "master" && docker build --no-cache -t v4rakh/gan-server:latest .
#  - test $TRAVIS_BRANCH = "master" && echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
#  - test $TRAVIS_BRANCH = "master" && docker push v4rakh/gan-server:latest
